Repository rolling-paper-toy/back-end, pull requests merged in 2024-11, with the labels that each got.

#71 [Refactor/token-delivery] JWT 토큰 전달 방식 개선
  src/main/java/com/sparklenote/user/handler/CustomSuccessHandler.java
Labels: 🔨 refactor, 🔗 api

#72 [Refactor/token-delivery] JWT 토큰 전달 방식 개선
  .env.template
  .idea/misc.xml
  build.gradle
  docker-compose.yml
  dockerfile
  src/main/java/com/sparklenote/common/config/CorsMvcConfig.java
  src/main/java/com/sparklenote/common/config/SecurityConfig.java
  src/main/java/com/sparklenote/domain/entity/Roll.java
  src/main/java/com/sparklenote/domain/entity/Sticker.java
  src/main/java/com/sparklenote/paper/controller/PaperController.java
  src/main/java/com/sparklenote/paper/service/PaperService.java
  src/main/java/com/sparklenote/roll/controller/RollController.java
  src/main/java/com/sparklenote/roll/dto/request/RollUpdateRequestDto.java
  src/main/java/com/sparklenote/roll/dto/response/RollJoinResponseDto.java
  src/main/java/com/sparklenote/roll/dto/response/RollResponseDTO.java
  src/main/java/com/sparklenote/roll/service/RollService.java
  src/main/java/com/sparklenote/user/controller/UserController.java
  src/main/java/com/sparklenote/user/handler/CustomLogoutHandler.java
  src/main/java/com/sparklenote/user/jwt/JWTFilter.java
  src/main/java/com/sparklenote/user/jwt/JWTUtil.java
  src/main/java/com/sparklenote/user/oAuth2/CustomOAuth2UserService.java
  src/main/java/com/sparklenote/user/service/UserService.java
  src/main/resources/prometheus.yml
  src/test/java/com/sparklenote/roll/controller/RollControllerTest.java
Labels: 🔨 refactor, 🐛 bugfix, 🔗 api

#75 [Refactor]/roll join
  src/main/java/com/sparklenote/common/config/SecurityConfig.java
  src/main/java/com/sparklenote/common/error/code/RollErrorCode.java
  src/main/java/com/sparklenote/domain/entity/Roll.java
  src/main/java/com/sparklenote/roll/dto/request/RollJoinRequestDto.java
  src/main/java/com/sparklenote/roll/dto/response/RollJoinResponseDto.java
  src/main/java/com/sparklenote/roll/service/RollService.java
Labels: 🔨 refactor

#76 Refactor/roll join & jwt-token-role-mapping
  src/main/java/com/sparklenote/domain/repository/StudentRepository.java
  src/main/java/com/sparklenote/paper/controller/PaperController.java
  src/main/java/com/sparklenote/paper/service/PaperService.java
  src/main/java/com/sparklenote/roll/service/RollService.java
  src/main/java/com/sparklenote/user/controller/UserController.java
  src/main/java/com/sparklenote/user/dto/response/UserInfoResponseDTO.java
  src/main/java/com/sparklenote/user/jwt/JWTFilter.java
  src/main/java/com/sparklenote/user/oAuth2/CustomOAuth2User.java
  src/main/java/com/sparklenote/user/oAuth2/CustomOAuth2UserService.java
  src/main/java/com/sparklenote/user/service/UserService.java
  src/main/java/com/sparklenote/user/student/CustomStudentDetails.java
  src/main/java/com/sparklenote/user/student/StudentDetailService.java
  src/main/java/com/sparklenote/user/student/dto/StudentResponseDTO.java
Labels: ✨ feature, 🔨 refactor, ⚙️ setting

#77 [refactor]: JWT 토큰 생성 및 권한 처리 로직 개선
  src/main/java/com/sparklenote/roll/service/RollService.java
  src/main/java/com/sparklenote/user/handler/CustomSuccessHandler.java
  src/main/java/com/sparklenote/user/jwt/JWTFilter.java
  src/main/java/com/sparklenote/user/jwt/JWTUtil.java
  src/main/java/com/sparklenote/user/service/UserService.java
Labels: 🔨 refactor

#85 Refactor/roll test Controller 테스트 코드 재작성 & Controller @PathVariable name 속성 추가
  src/main/java/com/sparklenote/domain/entity/Roll.java
  src/main/java/com/sparklenote/roll/controller/RollController.java
  src/main/java/com/sparklenote/roll/dto/response/RollJoinResponseDto.java
  src/main/java/com/sparklenote/roll/service/RollService.java
  src/test/java/com/sparklenote/roll/controller/RollControllerTest.java
  src/test/java/com/sparklenote/roll/service/RollServiceTest.java
Labels: 🔨 refactor, ✅ test

#90 Refactor/roll test : Roll Service 단위 테스트 완료 (18개 테스트 케이스)
  src/main/java/com/sparklenote/common/error/code/RollErrorCode.java
  src/main/java/com/sparklenote/roll/dto/request/RollUpdateRequestDto.java
  src/test/java/com/sparklenote/roll/service/RollServiceTest.java
Labels: ✅ test

#94 Feature/GitHub action setup
  .github/workflows/gradle.yml
Labels: 🌍 deploy, 🛠️ config

#96 Refactor/roll 학생 이름 공백 제거
  src/main/java/com/sparklenote/roll/dto/request/RollJoinRequestDto.java
Labels: 🔨 refactor

#100 Refactor/add role
  src/main/java/com/sparklenote/roll/dto/response/RollJoinResponseDto.java
  src/main/java/com/sparklenote/roll/service/RollService.java
  src/main/java/com/sparklenote/user/dto/response/UserInfoResponseDTO.java
  src/main/java/com/sparklenote/user/service/UserService.java
Labels: 🔨 refactor

#104 Refactor/security 엔드포인트 수정 (SpringSecurity)
  src/main/java/com/sparklenote/common/config/SecurityConfig.java
Labels: 🔨 refactor

#107 Refactor/security student 패키지 구조 변경
  src/main/java/com/sparklenote/common/config/SecurityConfig.java
  src/main/java/com/sparklenote/paper/service/PaperService.java
  src/main/java/com/sparklenote/roll/controller/RollController.java
  src/main/java/com/sparklenote/student/controller/StudentController.java
  src/main/java/com/sparklenote/student/dto/response/StudentResponseDTO.java
  src/main/java/com/sparklenote/student/service/StudentDetailService.java
  src/main/java/com/sparklenote/student/userDetails/CustomStudentDetails.java
  src/main/java/com/sparklenote/user/jwt/JWTFilter.java
Labels: 🔨 refactor

#109 Refactor/security JWT Filter 수정
  src/main/java/com/sparklenote/common/config/SecurityConfig.java
  src/main/java/com/sparklenote/user/jwt/JWTFilter.java
Labels: 🔨 refactor

#110 Refactor/security
  src/main/java/com/sparklenote/common/config/SecurityConfig.java
  src/main/java/com/sparklenote/roll/controller/RollController.java
  src/main/java/com/sparklenote/user/jwt/JWTFilter.java
  src/test/java/com/sparklenote/roll/controller/RollControllerTest.java
Labels: 🔨 refactor

#111 refactor : Immutable Collection 제거 (배포 서버 다운)
  src/main/java/com/sparklenote/common/config/SecurityConfig.java
Labels: 🐛 bugfix
