Repository rolling-paper-toy/back-end, pull requests merged in 2024-10, with the labels that each got.

#11 [refactor] annotation setting 추가
  .idea/misc.xml
  .idea/modules.xml
  .idea/rolling-paper-backend.iml
  build.gradle
  gradlew
  src/main/java/com/sparklenote/common/config/SecurityConfig.java
  src/main/java/com/sparklenote/common/config/SwaggerConfig.java
  src/main/java/com/sparklenote/paper/controller/PaperController.java
  src/main/java/com/sparklenote/paper/service/PaperService.java
  src/main/java/com/sparklenote/roll/controller/RollController.java
  src/main/java/com/sparklenote/roll/dto/request/RollRequestDTO.java
  src/main/java/com/sparklenote/roll/dto/response/RollResponseDTO.java
  src/main/java/com/sparklenote/roll/service/RollService.java
  src/main/java/com/sparklenote/sticker/controller/StickerController.java
  src/main/java/com/sparklenote/sticker/service/StickerService.java
  src/main/java/com/sparklenote/user/controller/MainController.java
  src/main/java/com/sparklenote/user/controller/MyController.java
  src/main/java/com/sparklenote/user/controller/UserController.java
  src/main/java/com/sparklenote/user/dto/request/UserRequestDTO.java
  src/main/java/com/sparklenote/user/service/UserService.java
Labels: 🔨 refactor, ⚙️ setting

#12 Feature/social login (카카오톡 소셜로그인 기능 구현 및 코드 리팩토링)
  .gitignore
  build.gradle
  src/main/java/com/sparklenote/common/config/SecurityConfig.java
  src/main/java/com/sparklenote/user/controller/MainController.java
  src/main/java/com/sparklenote/user/controller/UserController.java
  src/main/java/com/sparklenote/user/dto/response/KakaoResponse.java
  src/main/java/com/sparklenote/user/handler/CustomSuccessHandler.java
  src/main/java/com/sparklenote/user/jwt/JWTFilter.java
  src/main/java/com/sparklenote/user/jwt/JWTUtil.java
  src/main/java/com/sparklenote/user/oAuth/CustomOAuth2User.java
  src/main/java/com/sparklenote/user/oAuth/CustomOAuth2UserService.java
  src/main/resources/application.properties
Labels: ✨ feature, 🔨 refactor

#15 Feature/social login 병합 해결 및 패키지 명 변경
  .gitignore
  src/main/java/com/sparklenote/user/controller/MainController.java
  src/main/java/com/sparklenote/user/handler/CustomSuccessHandler.java
  src/main/java/com/sparklenote/user/jwt/JWTFilter.java
  src/main/java/com/sparklenote/user/jwt/JWTUtil.java
  src/main/java/com/sparklenote/user/oAuth/CustomOAuth2User.java
  src/main/java/com/sparklenote/user/oAuth/CustomOAuth2UserService.java
  src/main/java/com/sparklenote/user/oAuth2/CustomOAuth2User.java
Labels: 🔨 refactor

#17 Feature/create/roll
  build.gradle
  src/main/java/com/sparklenote/common/config/SecurityConfig.java
  src/main/java/com/sparklenote/common/config/SwaggerConfig.java
  src/main/java/com/sparklenote/common/response/SnResponse.java
  src/main/java/com/sparklenote/domain/entity/Paper.java
  src/main/java/com/sparklenote/domain/entity/Roll.java
  src/main/java/com/sparklenote/domain/entity/Sticker.java
  src/main/java/com/sparklenote/domain/entity/User.java
  src/main/java/com/sparklenote/domain/repository/RollRepository.java
  src/main/java/com/sparklenote/domain/repository/UserRepository.java
  src/main/java/com/sparklenote/roll/controller/RollController.java
  src/main/java/com/sparklenote/roll/dto/request/RollCreateRequestDto.java
  src/main/java/com/sparklenote/roll/dto/response/RollResponseDTO.java
  src/main/java/com/sparklenote/roll/service/RollService.java
  src/main/java/com/sparklenote/roll/util/ClassCodeGenerator.java
  src/main/java/com/sparklenote/roll/util/UrlGenerator.java
  src/main/java/com/sparklenote/user/controller/UserController.java
  src/main/java/com/sparklenote/user/oAuth2/CustomOAuth2UserService.java
Labels: ✨ feature, 🔨 refactor, 🛠️ config

#24 Feature/paper update 기능 구현
  src/main/java/com/sparklenote/paper/controller/PaperController.java
  src/main/java/com/sparklenote/paper/service/PaperService.java
Labels: ✨ feature

#27 Feature/paper read 기능 구현
  src/main/java/com/sparklenote/domain/repository/PaperRepository.java
  src/main/java/com/sparklenote/paper/controller/PaperController.java
  src/main/java/com/sparklenote/paper/service/PaperService.java
Labels: ✨ feature

#30 Feature/social login 리팩토링 및 기능 추가
  build.gradle
  src/main/java/com/sparklenote/common/config/SecurityConfig.java
  src/main/java/com/sparklenote/user/controller/UserController.java
  src/main/java/com/sparklenote/user/dto/request/TokenRequestDTO.java
  src/main/java/com/sparklenote/user/dto/response/TokenResponseDTO.java
  src/main/java/com/sparklenote/user/handler/CustomSuccessHandler.java
  src/main/java/com/sparklenote/user/jwt/JWTUtil.java
  src/main/java/com/sparklenote/user/service/UserService.java
  src/main/resources/application.properties
Labels: ✨ feature, 🔨 refactor

#33 Feature/redis setup
  build.gradle
  src/main/java/com/sparklenote/common/config/RedisConfig.java
  src/main/java/com/sparklenote/user/service/UserService.java
  src/main/resources/application.properties
Labels: 🛠️ config

#35 Feature/logout 기능 구현
  src/main/java/com/sparklenote/common/config/SecurityConfig.java
  src/main/java/com/sparklenote/user/controller/UserController.java
  src/main/java/com/sparklenote/user/dto/response/BlacklistResponseDTO.java
  src/main/java/com/sparklenote/user/handler/CustomLogoutHandler.java
Labels: ✨ feature, 🛠️ config

#36 Feature/logout Controller에 Swagger 설정 추가
  src/main/java/com/sparklenote/paper/controller/PaperController.java
  src/main/java/com/sparklenote/user/controller/UserController.java
  src/main/java/com/sparklenote/user/jwt/JWTFilter.java
Labels: 🔨 refactor

#37 [Feature]/ URL로 Roll 입장 이후 학급 코드 입력 후 입장
  src/main/java/com/sparklenote/SwaggerController.java
  src/main/java/com/sparklenote/domain/entity/Roll.java
  src/main/java/com/sparklenote/domain/entity/User.java
  src/main/java/com/sparklenote/domain/repository/RollRepository.java
  src/main/java/com/sparklenote/roll/controller/RollController.java
  src/main/java/com/sparklenote/roll/dto/request/RollJoinRequestDto.java
  src/main/java/com/sparklenote/roll/dto/response/RollJoinResponseDto.java
  src/main/java/com/sparklenote/roll/dto/response/RollResponseDTO.java
  src/main/java/com/sparklenote/roll/service/RollService.java
Labels: ✨ feature

#42 Feature/student login 기능 구현
  src/main/java/com/sparklenote/domain/entity/Student.java
  src/main/java/com/sparklenote/domain/repository/StudentRepository.java
  src/main/java/com/sparklenote/roll/dto/request/RollJoinRequestDto.java
  src/main/java/com/sparklenote/roll/dto/response/RollJoinResponseDto.java
  src/main/java/com/sparklenote/roll/service/RollService.java
  src/main/java/com/sparklenote/user/jwt/JWTFilter.java
Labels: ✨ feature, 🔨 refactor

#44 Feature/student login 로직 수정 및 기능 테스트 완료
  src/main/java/com/sparklenote/domain/entity/Paper.java
  src/main/java/com/sparklenote/domain/entity/Roll.java
  src/main/java/com/sparklenote/domain/entity/Sticker.java
  src/main/java/com/sparklenote/domain/entity/Student.java
  src/main/java/com/sparklenote/domain/entity/User.java
  src/main/java/com/sparklenote/paper/service/PaperService.java
  src/main/java/com/sparklenote/roll/controller/RollController.java
  src/main/java/com/sparklenote/roll/dto/request/RollJoinRequestDto.java
  src/main/java/com/sparklenote/roll/service/RollService.java
  src/main/java/com/sparklenote/roll/util/UrlGenerator.java
Labels: ✨ feature, 🔨 refactor

#51 Feature/exception 환경 설정 및 로그 관리
  .gitignore
  src/main/java/com/sparklenote/common/error/GlobalErrorHandler.java
  src/main/java/com/sparklenote/common/error/code/BaseErrorCode.java
  src/main/java/com/sparklenote/common/error/code/GlobalErrorCode.java
  src/main/java/com/sparklenote/common/error/code/PaperErrorCode.java
  src/main/java/com/sparklenote/common/error/code/RollErrorCode.java
  src/main/java/com/sparklenote/common/error/code/UserErrorCode.java
  src/main/java/com/sparklenote/common/error/response/ErrorResponse.java
  src/main/java/com/sparklenote/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparklenote/common/exception/PaperException.java
  src/main/java/com/sparklenote/common/exception/RollException.java
  src/main/java/com/sparklenote/common/exception/UserException.java
  src/main/java/com/sparklenote/paper/service/PaperService.java
  src/main/java/com/sparklenote/roll/service/RollService.java
  src/main/java/com/sparklenote/user/service/UserService.java
  src/main/resources/logback-spring.xml
Labels: ✨ feature, 🛠️ config

#54 feat : /user/info API 호출 시 사용자의 userId, name 반환
  src/main/java/com/sparklenote/user/controller/UserController.java
  src/main/java/com/sparklenote/user/dto/response/UserResponseDTO.java
  src/main/java/com/sparklenote/user/service/UserService.java
Labels: 🔨 refactor

#56 [Feature] Roll List 조회 구현
  src/main/java/com/sparklenote/domain/repository/RollRepository.java
  src/main/java/com/sparklenote/paper/service/PaperService.java
  src/main/java/com/sparklenote/roll/controller/RollController.java
  src/main/java/com/sparklenote/roll/service/RollService.java
Labels: ✨ feature, 🔨 refactor

#59 Refactor/Roll - Create 단위 테스트 & 통합 테스트 구현
  src/main/java/com/sparklenote/paper/service/PaperService.java
  src/main/java/com/sparklenote/user/dto/response/UserResponseDTO.java
  src/test/java/com/sparklenote/roll/controller/RollControllerTest.java
  src/test/java/com/sparklenote/roll/service/RollServiceTest.java
Labels: ✅ test

#61 Refactor/user /user/info API 수정
  src/main/java/com/sparklenote/common/error/code/UserErrorCode.java
  src/main/java/com/sparklenote/paper/service/PaperService.java
  src/main/java/com/sparklenote/user/controller/UserController.java
  src/main/java/com/sparklenote/user/service/UserService.java
Labels: 🔨 refactor

#62 Refactor/roll -> Roll 관련 기능 테스트 코드 추가
  src/main/java/com/sparklenote/common/code/GlobalSuccessCode.java
  src/main/java/com/sparklenote/common/config/SecurityConfig.java
  src/main/java/com/sparklenote/common/error/code/RollErrorCode.java
  src/main/java/com/sparklenote/roll/controller/RollController.java
  src/main/java/com/sparklenote/roll/dto/request/RollCreateRequestDto.java
  src/main/java/com/sparklenote/roll/dto/request/RollJoinRequestDto.java
  src/main/java/com/sparklenote/roll/service/RollService.java
  src/main/java/com/sparklenote/user/handler/CustomLogoutHandler.java
  src/main/java/com/sparklenote/user/handler/CustomSuccessHandler.java
  src/main/java/com/sparklenote/user/service/UserService.java
  src/test/java/com/sparklenote/roll/controller/RollControllerTest.java
Labels: 🔨 refactor, ✅ test
